// Generated by Apple Swift version 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_attribute(external_source_symbol)
# define SWIFT_STRINGIFY(str) #str
# define SWIFT_MODULE_NAMESPACE_PUSH(module_name) _Pragma(SWIFT_STRINGIFY(clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in=module_name, generated_declaration))), apply_to=any(function, enum, objc_interface, objc_category, objc_protocol))))
# define SWIFT_MODULE_NAMESPACE_POP _Pragma("clang attribute pop")
#else
# define SWIFT_MODULE_NAMESPACE_PUSH(module_name)
# define SWIFT_MODULE_NAMESPACE_POP
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR __attribute__((enum_extensibility(open)))
# else
#  define SWIFT_ENUM_ATTR
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_ATTR SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if __has_feature(modules)
@import AVFoundation;
@import UIKit;
@import CoreGraphics;
@import ObjectiveC;
@import Foundation;
@import ZendeskProviderSDK;
#endif

#import <ZendeskSDK/ZendeskSDK.h>

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

SWIFT_MODULE_NAMESPACE_PUSH("ZendeskSDK")






@class NSCoder;

/// Main Support SDK image picker that looks similar to the message.app one
/// TODO make internal before releasing
SWIFT_CLASS("_TtC10ZendeskSDK18AwesomeImagePicker")
@interface AwesomeImagePicker : UIView
- (void)didMoveToWindow;
@property (nonatomic, readonly) CGSize intrinsicContentSize;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end



/// Enum that represents the file types that zendesk supports
typedef SWIFT_ENUM_NAMED(NSInteger, ZDKFileType, "FileType") {
  ZDKFileTypePng = 0,
  ZDKFileTypeJpg = 1,
  ZDKFileTypePdf = 2,
  ZDKFileTypePlain = 3,
  ZDKFileTypeWord = 4,
  ZDKFileTypeExcel = 5,
  ZDKFileTypePowerpoint = 6,
  ZDKFileTypePowerpointX = 7,
  ZDKFileTypeKeynote = 8,
  ZDKFileTypePages = 9,
  ZDKFileTypeNumbers = 10,
  ZDKFileTypeBinary = 11,
};

@class ZDKHelpCenterArticleRatingView;

SWIFT_CLASS("_TtC10ZendeskSDK30HelpCenterArticleVotingHandler")
@interface HelpCenterArticleVotingHandler : NSObject <ZDKHelpCenterArticleRatingHandlerProtocol>
- (nonnull instancetype)initWithArticleId:(NSInteger)articleId andLocale:(NSString * _Nonnull)locale;
- (void)articleRatingVoteSelected:(ZDKHelpCenterArticleRatingView * _Nonnull)ratingView atIndex:(NSInteger)index;
- (NSInteger)currentArticleVote SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end






/// Creates an attachment to be uploaded when a request is created
SWIFT_CLASS_NAMED("RequestAttachment")
@interface ZDKRequestAttachment : NSObject
/// Name of the file to be uploaded
@property (nonatomic, readonly, copy) NSString * _Nonnull filename;
/// Data of the file contents to be uploaded
@property (nonatomic, readonly, copy) NSData * _Nonnull data;
/// Type of the file to be uploaded
@property (nonatomic, readonly) enum ZDKFileType fileType;
/// Generates a new state from the old state and an action
/// \param filename the name of the file to be uploaded, without the file extension
///
/// \param data the data of the contents of the file to be uploaded
///
/// \param fileType the type of the file to be uploaded
///
///
/// returns:
/// an instance of RequestAttachment
- (nonnull instancetype)initWithFilename:(NSString * _Nonnull)filename data:(NSData * _Nonnull)data fileType:(enum ZDKFileType)fileType OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

@class NSBundle;

/// Request controller representing the main view controller for request
SWIFT_CLASS("_TtC10ZendeskSDK17RequestController")
@interface RequestController : UIViewController
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)viewWillDisappear:(BOOL)animated;
- (void)viewDidAppear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end







@protocol UIViewControllerPreviewing;

@interface RequestController (SWIFT_EXTENSION(ZendeskSDK)) <UIViewControllerPreviewingDelegate>
/// Peek and pop implementation
- (UIViewController * _Nullable)previewingContext:(id <UIViewControllerPreviewing> _Nonnull)previewingContext viewControllerForLocation:(CGPoint)location SWIFT_WARN_UNUSED_RESULT;
- (void)previewingContext:(id <UIViewControllerPreviewing> _Nonnull)previewingContext commitViewController:(UIViewController * _Nonnull)viewControllerToCommit;
@end



@protocol UIViewControllerTransitionCoordinator;

SWIFT_CLASS("_TtC10ZendeskSDK25RequestListViewController")
@interface RequestListViewController : UIViewController
- (void)viewDidLoad;
- (void)viewWillDisappear:(BOOL)animated;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillTransitionToSize:(CGSize)size withTransitionCoordinator:(id <UIViewControllerTransitionCoordinator> _Nonnull)coordinator;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end






























SWIFT_CLASS("_TtC10ZendeskSDK12ZDKConstants")
@interface ZDKConstants : NSObject
+ (UIColor * _Nonnull)colorForToast SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



@protocol ZDKUiConfiguration;
@class UINavigationController;

SWIFT_CLASS("_TtC10ZendeskSDK12ZDKRequestUi")
@interface ZDKRequestUi : NSObject
/// Presents the Conversations screen on top of the view controller modally.
/// since:
/// 2.0.0.0
/// \param viewcontroller the UIViewController, or subclass, to present from
///
/// \param configuration the ZendeskUiConfig used when creating a ticket. Can be nil
///
+ (void)presentRequestControllerWith:(UIViewController * _Nullable)viewcontroller configurations:(NSArray<id <ZDKUiConfiguration>> * _Nullable)configurations;
/// Presents the Conversations screen on top of the view controller modally.
/// since:
/// 2.0.0.0
/// \param viewcontroller the UIViewController, or subclass, to present from
///
/// \param configuration the ZendeskUiConfig used when creating a ticket. Can be nil
///
/// \param requestID the ID of the Zendesk request to open. Passing nil creates a new request.
///
+ (void)presentRequestControllerWith:(UIViewController * _Nullable)viewcontroller configurations:(NSArray<id <ZDKUiConfiguration>> * _Nullable)configurations requestID:(NSString * _Nullable)requestID;
+ (void)pushRequestControllerWith:(UINavigationController * _Nullable)navigationController configurations:(NSArray<id <ZDKUiConfiguration>> * _Nullable)configurations;
/// Push the Conversations screen on top of the navigation stack.
/// since:
/// 2.0.0.0
/// \param navigationController the UINavigationController, or subclass, to push from.
///
/// \param configuration the ZendeskUiConfig used when creating a ticket. Can be nil.
///
/// \param requestID the ID of the Zendesk request to open. Passing nil creates a new request.
///
+ (void)pushRequestControllerWith:(UINavigationController * _Nullable)navigationController configurations:(NSArray<id <ZDKUiConfiguration>> * _Nullable)configurations requestID:(NSString * _Nullable)requestID;
+ (void)presentRequestListWith:(UIViewController * _Nullable)viewcontroller configurations:(NSArray<id <ZDKUiConfiguration>> * _Nullable)configurations;
/// Push the Request List screen on top of the navigation stack.
/// since:
/// 2.0.0.0
/// \param navigationController the UINavigationController, or subclass, to push from.
///
/// \param configuration the ZendeskUiConfig used when creating a ticket. Can be nil.
///
+ (void)pushRequestListWith:(UINavigationController * _Nullable)navigationController configurations:(NSArray<id <ZDKUiConfiguration>> * _Nullable)configurations;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



@class ZDKCustomField;
@class NSNumber;

SWIFT_CLASS("_TtC10ZendeskSDK25ZDKRequestUiConfiguration")
@interface ZDKRequestUiConfiguration : NSObject <ZDKUiConfiguration>
@property (nonatomic, copy) NSString * _Nonnull subject;
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull tags;
@property (nonatomic, copy) NSArray<ZDKCustomField *> * _Nonnull fields;
@property (nonatomic, strong) NSNumber * _Nullable ticketFormID;
@property (nonatomic, copy) NSArray<ZDKRequestAttachment *> * _Nonnull fileAttachments;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




/// This class is just a workaround and it should be removed when core provides a way to access the action registry from objective c
SWIFT_CLASS("_TtC10ZendeskSDK17ZendeskWrapperUIX")
@interface ZendeskWrapperUIX : NSObject
+ (void)setupActionHandlers;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_MODULE_NAMESPACE_POP
#pragma clang diagnostic pop
